### PR TITLE
Rework code to decouple Item/CodeHandler memory offsets

### PR DESCRIPTION
**Pull request by rabbitt**
- adds [YamlDotNet](https://github.com/aaubry/YamlDotNet) library as it's more flexible than JSON when it comes to integer types (e.g., it supports hexadecimal notation, etc.)
- adds an offsets.yaml which contains the memory offsets for the codehandler and items
- converts items.json to items.yaml, leveraging YamlDotNet for loading the data
- embeds (via resources) both offsets.yaml and items.yaml
- provides three mechanisms for fetching a resource (e.g., offsets.yaml, or items.yaml), in order of lookup:
  1. looks for the resource in the same directory as the executable
  2. looks for the resource in the embedded resources data
  3. falls back to fetching the resource from the github page directly
- removed all references to json, though not the json package itself
- adds a user specific setting, BotwVersion, for storing the last known game version
- I have no empirical evidence to back it up, but it certainly _feels_ faster loading items without json in the mix.

P.s. I'm not married to any of this, so feel free to take it and butcher it if you like. Also note, my experience with C# is a bit limited (mostly just toying around with Unity/Mono) - please forgive any obvious design flaws/code smells.

### CODE REVIEW

**Comment by rabbitt** [comment]
@joffnerd Any thoughts on this - e.g., right track, poor implementation; not going there, don't bother; good stuff, keep going; don't have time for this, leave me alone ..? :-)

**Comment by joffnerd** [comment]
Thanks, sorry I hadn't seen the PR! I am going to pull it into a b ranch and test locally to get a feel for what you have done.

**Comment by rabbitt** [comment]
@joffnerd btw, I did some hackish stuff in `Offsets` to get around having to create a custom YamlDotNet converter/deserializer. Time permitting (likely after kids are in bed tonight), I'll go through and comment those areas of the code with `FIXME` / `XXX` comments. :-)

**Comment by joffnerd** [comment]
I just pulled, edited slightly and pushed to the repo. Can you pull again before doing more?

Thanks man

P.S. Are you on gbatemp forums?

**Comment by rabbitt** [comment]
Thanks for taking the PR! I'll be sure to pull from master and open a new branch for adding the comments. I noticed in your changes included a bunch of variable/property renames. What's the standard naming convention in C# for properties vs variables, etc?

Re: gbatemp - I'm not on there currently but I can be...

Cheers!

**Pull request merged**
