### PR TITLE
Appveyor CI build artifacts

### PR DESCRIPTION
**Pull request by mancoast**
REF:
https://ci.appveyor.com/project/mancoast/botw-trainer

### CODE REVIEW

**Comment by mancoast** [comment]
@joffnerd Continuous Integration assures that the build system compiles in a generic cloud hosted virtual machine.  The results of the cloud compilation operations are available as zip build-package artifacts.  Appveyor is a separate service from GITHUB, but the two services inter-operate through authorization of access to GIT HOOKS.  The hooks enable a new build foreach commit.

**Comment by mancoast** [comment]
resolves https://github.com/joffnerd/botw-trainer/issues/65

**Comment by joffnerd** [comment]
Thanks but its just a basic trainer, not a big commercial app that needs continuous integration. Happy to build myself.

**Comment by mancoast** [comment]
Greetings,

The current msbuild configuration is broken.
Appveyor is a generic virtual machine.
Compilation on the generic machine garentees that others, like myself, can download and compile.
In the current state, the code does not compile. [perhaps there is something special on your machine?]
These changes supply the appveyor configuration, && changes to fix compilation.
Essentially, you need to remove the ignored 'notes.txt' from the solution. [breaks build]
Also, the nuget for JSON is targeting .NET4.5
Update JSON nuget to v. 10 to target correlating .NET462.

Thanks,
coast

**Comment by mancoast** [comment]
BTW appveyor is **free** for open-source projects.  Now that your code is MIT License, you can use appveyor for free with botw-trainer.  It's easy to use cloud compilation.

**Comment by joffnerd** [comment]
I have updated json and removed notes from solution

**Comment by mancoast** [comment]
Thanks! I will retest with the latest changes.

Additionally the repo also needs a NuGet.config in the root.
This will automatically resolve the DLL references using the 'hint'.

REF: https://github.com/buddhi1980/mandelbulber2/blob/master/NuGet.config

**Pull request closed without merging**
